name: Validate Swagger Documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  swagger-validation:
    name: Validate Swagger Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate Swagger Documentation
        run: php artisan l5:generate

      # Aqui você pode adicionar comandos para validar a documentação do Swagger
